name: Build and Deploy
on:
  push:
    branches:
      - main
permissions:
  contents: write
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Install Dependencies
        run: sudo apt-get update && sudo apt-get install -y ninja-build cmake
          
      - name: Setup Emscripten
        uses: mymindstorm/setup-emsdk@v14
        with:
          version: 3.1.45
          actions-cache-folder: emsdk-cache

      - name: Build
        run: |
          mkdir build
          emcmake cmake -S . -B build -GNinja -DCMAKE_BUILD_TYPE=Release
          emmake ninja -C build

      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: build/Release/
          
          
